### PR TITLE
remove the mvn dependency from the end2end sample

### PR DESCRIPTION
**Pull request by lilyhe123**
Use `jar` to build the test webapp, instead of `mvn`. Also, do this in a temporary docker container so no `jar` or `jdk` need to be installed to the host machine.

### CODE REVIEW

**Comment by lilyhe123** [comment]
> HI Lily, please make sure it passes jerking http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3829/ in the params put class ItMonitoringExporter, branch rm-mvn for MONITORING_EXPORTER_BRANCH, see that link as example. Somehow it fails to create to build app.
> Also add 2020 copyrights to all changed files

**Comment by lilyhe123** [comment]
> HI Lily, please make sure it passes jerking http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3829/ in the params put class ItMonitoringExporter, branch rm-mvn for MONITORING_EXPORTER_BRANCH, see that link as example. Somehow it fails to create to build app.

Run the tests with/without my change. Got the same result: 0 failures , 3 skipped.
Result without my change: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3869/testReport/.
Result with my change: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3868/testReport/.

> Also add 2020 copyrights to all changed files.

Fixed.

**Comment by marinakog** [comment]
> > HI Lily, please make sure it passes jerking http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3829/ in the params put class ItMonitoringExporter, branch rm-mvn for MONITORING_EXPORTER_BRANCH, see that link as example. Somehow it fails to create to build app.
> 
> Run the tests with/without my change. Got the same result: 0 failures , 3 skipped.
> Result without my change: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3869/testReport/.
> Result with my change: http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3868/testReport/.
> 
> > Also add 2020 copyrights to all changed files.
> 
> Fixed.

you did not unselect QuitTest option, so ItMonitorinExporter tests are skipped
see params for correct run  http://wls-jenkins.us.oracle.com/job/weblogic-kubernetes-operator-javatest/3870/parameters/

**Comment by ddsharpe** [comment]
Please try to update this PR so we can get it merged.  There have been no updates in 2 months!

**Comment by ddsharpe** [comment]
This PR does not appear to be needed any more.  Closing due to inactivity.

**Pull request closed without merging**
